// vuejs-crash-course/src/components/AddTodo.vue
<template>
  <div>
    <form @submit="addTodo">
      <input type="text" name="title" v-model="title" placeholder="Add Todo...">
      <input type="submit" value="Submit" class="btn">
    </form>
  </div>    
</template>

<script>

export default {
    name: "AddTodo",
    data() {
      return {
        title: ''
      }
    },
    methods: {
      addTodo(e) {
        e.preventDefault();
        const newTodo = {
          title: this.title,
          completed: false
        }
        // Send up to parent
        this.$emit('add-todo', newTodo);
        this.title = '';
      }

    }
}
</script>

<style scoped>
  form {
    display: flex;
  }

  input[type="text"] {
    flex: 10;
    padding: 5px;
  }

  input[type="submit"] {
    flex: 2;
  }
</style>

// reactjs-crash-course/src/components/AddTodo.js
import React, { Component } from 'react'
import PropTypes from 'prop-types';

export class AddTodo extends Component {
  state = {
    title: ''
  }

  onChange = (e) => this.setState({ [e.target.name]: e.target.value });

  onSubmit = (e) => {
    e.preventDefault();
    this.props.addTodo(this.state.title);
    this.setState({ title: ''});
  }
  render() {
    return (
        <form onSubmit={this.onSubmit} style={{ display: 'flex' }}>
          <input 
            type="text" 
            name="title" 
            placeholder="Add Todo ..." 
            style={{ flex: '10', padding: '5px' }} 
            value={this.state.title}
            onChange={this.onChange}
          />
          <input 
            type="submit" 
            value="submit" 
            className="btn" 
            style={{ flex: '1' }}
          />
        </form>
    )
  }
}

// PropType
AddTodo.propTypes = {
  addTodo: PropTypes.func.isRequired
}

export default AddTodo
